--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/TNTBlastRadius
build-by-default: true
branches:
- pm4
- pm 5
projects:
  TNTBlastRadius:
    path: ""
    icon: icon.gif
...
