--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Terpz710/TNTBlastRadius
build-by-default: true
branches:
- main
projects:
  TNTBlastRadius:
    path: ""
    icon: icon.png
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
...
