name: TNTBlastRadius
version: 1.0.2
api: [5.0.0]
main: Terpz710\TNTBlastRadius\Main
author: Terpz710
description: Edit TNT blast radius.
depend: [FormAPI]
permissions:
  tntradius.command:
    description: Allows players to use the /tntradius command.
    default: op
