name: TNTBlastRadius
version: 1.0.4
api: [5.0.0]
main: terpz710\tntblastRadius\Main
author: Terpz710
description: Edit the TNT blast radius.
permissions:
  tntblastradius.cmd:
    description: Allows players to use the command.
    default: op
